"""
File to manage constants for the process
"""
#TWITTER_CREDENTIALS_CONSTANTS
TWITTER_CONSUMER_KEY = "TWITTER_CONSUMER_KEY"
TWITTER_CONSUMER_SECRET = "TWITTER_CONSUMER_SECRET"
TWITTER_ACCESS_KEY = "952423405-TWITTER_ACCESS_KEY"
TWITTER_ACCESS_SECRET = "TWITTER_ACCESS_SECRET"
TWITTER_BEARER_TOKEN = "TWITTER_BEARER_TOKEN"

#FIREHOSE_DATA
STREAM_NAME = "test-twitter-stream"
CLIENT_FIREHOSE_NAME = "firehose"
MAX_CONNECTION_RETRIES = 10
MAX_CONNECTION_SLEEP = 60

#File management constants
CSV_FOLDER = "data/csv/"
JSON_FOLDER = "data/json/"
PARQUET_FOLDER = "data/parquet/"
CSV_EXTENSION = ".csv"
PARQUET_EXTENSION = ".parquet.gzip"
UTF8_ENCODING = "utf-8"
GZIP_COMPRESSION="gzip"
LOG_FOLDER = "logs/"
LOG_NAME = "twitter_stream"
LOG_EXTENSION = ".log"